import background from "./background.png";
import logo from './logo.png'
import c1 from './c1.JPG'
import c2 from './c2.JPG'
import c3 from './c3.JPG'
import c4 from './c4.JPG'
import c5 from './c5.JPG'
import c6 from './c6.JPG'
import thirdbg from './thirdbg.jpg'
import premlogo from './premlogo.JPG'
import zzpt from './zzpt.JPG'
import w1 from './w1.JPG'
import w2 from './w2.JPG'
import w3 from './w3.JPG'
import w4 from './w4.JPG'
import w5 from './w5.JPG'
import bgworks from './bgworks.png'
import gplay from './gplay.JPG'
import appstore from './appstore.JPG'
import e1 from './e1.JPG'
import e2 from './e2.JPG'
import e3 from './e3.JPG'
import e4 from './e4.JPG'
import e5 from './e5.JPG'
import quotes from './quotes.png'
import dq from './dq.png'
import n1 from './n1.JPG'
import n2 from './n2.JPG'
import n3 from './n3.JPG'
import n4 from './n4.JPG'
import n5 from './n5.JPG'
import n6 from './n6.JPG'
import n7 from './n7.JPG'
import n8 from './n8.JPG'
import l1 from './l1.JPG'
import l2 from './l2.JPG'
import l3 from './l3.JPG'
import l4 from './l4.JPG'
import t1 from './t1.JPG'
import t2 from './t2.JPG'
import t3 from './t3.JPG'
import t4 from './t4.JPG'
import carsbg from './carsbg.png'



export {
    background,logo,c1,c2,c3,c4,c5,c6,quotes,thirdbg,premlogo,zzpt,w1,w2,w3,w4,w5,bgworks,appstore,gplay,e1,e2,e3,e4,e5,dq,n1,n2,n3,n4,n5,n6,n7,n8,l1,l2,l3,l4,carsbg,t1,t2,t3,t4
}